### ISSUE TITLE
Patch update tool enhancements

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/BuildTools#194]
Consider the following:

- List updated and un-updated packages: parse the resulting patchconfig to get a list of packages that had a version update in this patch vs a list of packages that contained no version update.
- Ignore package: we may want to explicitly not update some packages since we won't ship updates, for example, pre-release packages during patches, tools when we build them separately. This will require changing the update dependency tool as well.
- Undo updates: nuclear option to undo a bad patch option. The patchconfig file retains all the information in terms of what version changes were made. This allows us to undo those changes if necessary. May be an useful pre-emptive feature
- Support .csproj: currently only project.json based projects are supported. Depending on how we plan to do patch updates, we may also need to support .csproj based projects as well.
- Interaction with other build artifacts/steps: consider automatically updating packages.csv with the correct list of packages to ship. Also potentially parse config.targets for a list of repos to update.

cc @pranavkm

**Comment by Eilon** [comment]
For the 2nd bullet point above:

We need to make sure we don't even recompile `src/` projects that didn't change in a patch. Some repos get updated for a patch just because their *test* projects need to be updated due to a test-only dependency that is part of a patch (e.g. NETCore.App). For those cases we need to use already-built packages from NuGet.org because that is the real scenario that we end up shipping.

For repos that are in this scenario we need to have a way of skipping building the `src` repos:
* For project.json repos, we could rename the 'src' folder to 'src-nobuild' (and then the project.json of the test projects would pull from NuGet.org).
* For csproj repos, in addition to renaming the `src` folder, we would write a target that remaps `src/**/*.csproj` `ProjectReference` elements to be `PackageReference` elements

**Comment by JunTaoLuo** [comment]
These update are no likely to be needed any longer. This was only needed for our 1.x patches, and we are not using the patch tool in our 2.0 infrastructure. Seeing how for 1.x, the current tool is sufficient, I'll close this issue. Feel free to reopen if you disagree.
