### ISSUE TITLE
Tools on .NET Core 2.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#200]
Will be a breaking change incompatible with .NET Core 1.0 CLI. Requires bumping tools package versions to 2.0.

Alternatively, we can make tasks run in-proc with MSBuild so they are runtime-agnostic. Would still require a 2.0 version bump.

**Comment by natemcmaster** [comment]
Btw, makes me happy that this is issue #200.

**Comment by natemcmaster** [comment]
cc @dougbu

**Comment by dougbu** [comment]
Removing myself here because this work isn't as related to getting ApiCheck.exe working again as we thought (see #205). In fact, we _cannot_ move ApiCheck.exe to netcoreapp2.0 until it is guaranteed to run using the exact target 2.0.0-* shared runtime or newer. (Probably need to build that executable against a specific shared runtime version that is guaranteed to be older than what KoreBuild targets that day.)

See branch `dougbu/netcoreapp2.0` for a commit that does part of the upgrade. Doesn't currently build because it contains changes originally done as part of #205.

This branch also does _not_ bump the package versions. That's necessary because we don't want newer tools used when building downlevel branches.

**Comment by dougbu** [comment]
On a related note, the VersionTool project is unable to consume the Microsoft.Extensions.CommandLineUtils.Sources package. It exposes `public` properties of some newly-`internal` types. Should address this while dealing with other versioning issues.

**Comment by natemcmaster** [comment]
@Eilon we should do this soon. The latest 2.0 builds of CLI no longer bundle .NET Core 1.0. MSBuild and dotnet CLI itself have completely upgraded to 2.0.

**Comment by Eilon** [comment]
But we can't do it soon, can we? We're blocked by the NuGet bug, no?

**Comment by Eilon** [comment]
Oh wait sorry this isn't about actual CLI tools, right? This is just about our own "projects" that are "command line tools"?

**Comment by natemcmaster** [comment]
Right. This is about our command line apps (e.g. NuGetPackageVerifier), not our DotnetCliToolReference packages (e.g. dotnet-watch).

**Comment by Eilon** [comment]
@dougbu said:
> In fact, we cannot move ApiCheck.exe to netcoreapp2.0 until it is guaranteed to run using the exact target 2.0.0-* shared runtime or newer.

What exactly does this mean? Is the concern that .NET Core 2.0 isn't stable enough yet?

**Comment by dougbu** [comment]
> What exactly does this mean?

The tool itself targets a particular shared runtime. If it's built for a _newer_ runtime than an assembly it needs to load, the tool just blows up.

When I wrote this, we hadn't completed the `netcoreapp2.0` transition. Not sure of the current status in all repos building using current packages from this repo.

**Comment by Eilon** [comment]
I think that given that all our tools obviously need at most what's in 1.0/1.1, there shouldn't be any problem migrating any to 2.0, right? That is, they can't possibly need anything that's new in 2.0 (yet).

**Comment by dougbu** [comment]
Agreed. My earlier [comment](https://github.com/aspnet/BuildTools/issues/200#issuecomment-288811670) was about why updating to `netcoreapp2.0` didn't fit w/ the API Check work I was doing.

**Comment by mikeharder** [comment]
What's the estimated cost of this?  If it's low we should probably just do it now.
