### ISSUE TITLE
Make IgnoreAssistanceMode.ShowAll the default in NuGetPackageVerifier

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/BuildTools#206]
Currently we need to pass `--verbose` to see IgnoreAssistance info. Since there is no way to pass arguments to NPV when running Build.cmd, we should make it show IgnoreAssistance data by default.

@Eilon @natemcmaster

**Comment by Eilon** [comment]
Any downsides at all to enabling it? I would think it's never "noise" because if it fails, you either have to fix what it told you to fix (ideal), or add the exclusion, in which case having the generated JSON there is helpful.

Thoughts?

**Comment by ajaybhargavb** [comment]
I just tested this out. The downside is that it shows ignore info about the packages we already have in the ignore list (i.e. if the json has an exclusion already specified, it still shows that as part of ignore assistance)

**Comment by Eilon** [comment]
Ah, that's broken then. It's supposed to print only new ones. As it runs, it's supposed to "cross off the list" any exclusions that were already excluded.

BTW instead of making this simply "the default," I'd like to get rid of having an *option* for this at all. That is, *always* show the JSON, no matter what.

**Comment by ajaybhargavb** [comment]
7d354547e0c866825721455003db94df1aa63790
