### ISSUE TITLE
Add a tool to automatically set required env variables for dogfooding

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#386]
KoreBuild doesn't always play nice with Visual Studio. We should look into adding a script that will automatically set PATH and anything else required to make it easier for contributors and devs on our team to build,dev,test in VS.

cc @bricelam  @smitpatel

**Comment by smitpatel** [comment]
> our team to build,dev,test in VS.

Isn't having ability to build/dev/test is separate from dogfooding?

**Comment by heku** [comment]
Hi @natemcmaster , glad to see you again. Today, I have tried lots of ways to set `%USERPROFILE%\.dotnet\x86` to `PATH` before build in VS, as I do want this path only adds to `PATH` when needed, but I failed, I have to change `PATH` from dotnet 2.0 to this so that VS works.
Below is one solution I suppose to work as I saw the tip message before, so it should be invoked by VS.
```xml
<Project InitialTargets="SetDotNetSDKPath;EnsureKoreBuildRestored">

  <Target Name="SetDotNetSDKPath">
    <Exec Command="set PATH=%USERPROFILE%\.dotnet\x86;%PATH%"></Exec>
  </Target>
  
  <Target Name="EnsureKoreBuildRestored" Condition=" '$(KoreBuildRestoreTargetsImported)' != 'true' ">
    <PropertyGroup>
      <_BootstrapperFile Condition=" $([MSBuild]::IsOSUnixLike()) ">build.sh</_BootstrapperFile>
      <_BootstrapperFile Condition="! $([MSBuild]::IsOSUnixLike()) ">build.cmd</_BootstrapperFile>
      <_BootstrapperError>
        Package references have not been pinned. Run './$(_BootstrapperFile) /t:Pin'.
        Also, you can run './$(_BootstrapperFile) /t:Restore' which will pin *and* restore packages. '$(_BootstrapperFile)' can be found in '$(MSBuildThisFileDirectory)'.
      </_BootstrapperError>
    </PropertyGroup>

    <Error Code="KRB1001" Text="$(_BootstrapperError.Trim())" />
  </Target>

</Project>
```
I saw your discussion around this in some other issues, if you have solution on this, please tell me, thank you very much.

**Comment by natemcmaster** [comment]
@heku thanks for the suggestion. I'll have to look into this more, but I suspect it won't quite work.  PATH needs to be set before VS opens so tooling that attempts to find dotnet.exe before MSBuild executes uses the right value. For example, Test Explorer and MSBuild's SDK Resolver.

**Comment by natemcmaster** [comment]
_Triage team:_ closing this as low priority.
