### ISSUE TITLE
Revisit assembly loading strategy/requirements for API check

### ISSUE THREAD

**Issue by javiercn** [aspnet/BuildTools#594]

**Comment by Eilon** [comment]
When it's time to work on this let's figure out if this should be part of https://github.com/dotnet/arcade along with other shared tools.

**Comment by natemcmaster** [comment]
Also, when it's time to work on it, consider looking at https://github.com/natemcmaster/AspNetBuildTools/tree/apicheck. This was my 75% done refactoring of the tool to use System.Reflection.Metadata.

**Comment by muratg** [comment]
Is this one done? If so, please close! (Moved to the next milestone in the meantime.)

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface. Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. See https://github.com/aspnet/BuildTools/issues/747
