### ISSUE TITLE
Add an additional MSBuild property RequiresBaseline/RequiresApiCheck

### ISSUE THREAD

**Issue by javiercn** [aspnet/BuildTools#614]
This property will also exclude API Check from running against the project but it has different semantics. This property mark a project as not requiring API Check and its meant for new libraries on a release and for prototypes vs EnableApiCheck which should only be used to disable it from running in case there is an issue with the tool.

**Comment by natemcmaster** [comment]
Another solution might be to just add empty baselines, but let's investigate more later.

**Comment by ryanbrandenburg** [comment]
@javiercn is this a required item?

**Comment by muratg** [comment]
Is this one done? If so, please close! (Moved to the next milestone in the meantime.)

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface. Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. See https://github.com/aspnet/BuildTools/issues/747
