### ISSUE TITLE
ApiCheck sometimes identifies classes as having been deleted when they were not.

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#615]
@javiercn and I identifier a case where ApiCheck thinks that a class which still exists unchanged has been removed. 

We get a message like:
```
The following types have been removed.

      public class Microsoft.Extensions.Logging.Abstractions.NullLogger<T0> : Microsoft.Extensions.Logging.ILogger<T0>
      public class Microsoft.Extensions.Logging.Abstractions.NullLoggerFactory : Microsoft.Extensions.Logging.ILoggerFactory
      public class Microsoft.Extensions.Logging.Abstractions.NullLoggerProvider : Microsoft.Extensions.Logging.ILoggerProvider
```

But when we look at those types they have not changed their namespace or name, they still exist in the dll and the interface they implement hasn't changed its signature either.

Once this is fixed we'll have to revert all the changes made to make things pass in the mean time.

**Comment by muratg** [comment]
Is this one done? If so, please close! (Moved to the next milestone in the meantime.)

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface. Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. See https://github.com/aspnet/BuildTools/issues/747
