### ISSUE TITLE
ApiCheck should not flag increasing visibility non virtual members as a breaking change

### ISSUE THREAD

**Issue by HaoK** [aspnet/BuildTools#622]
See https://github.com/aspnet/Identity/issues/1168

Rule: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#members

Basic idea is that the following should not be considered a breaking change

```
// Old
class Foo {
   protected const string Constant = "whatever";
}

// New
class Foo {
   public const string Constant = "whatever";
}
```

**Comment by Eilon** [comment]
Details of what the rule should be based on:

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#members

> Members
> ✓ Allowed
> 
> ...
> 
> Increasing the visibility of a member that is not virtual

**Comment by HaoK** [comment]
We did simultaneous edits of the title and of the rule :) @Eilon

**Comment by Eilon** [comment]
Oh haha that explains why GitHub was behaving crazy 😄

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface (see #747). Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. Please reopen if this is urgent.
