### ISSUE TITLE
VSTest output not displayed on console output on Windows

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#623]
After #621 , I'm not seeing console output from vstest

![image](https://user-images.githubusercontent.com/2696087/37999089-2259407a-31d6-11e8-99e5-d187e966caf7.png)

Doesn't appear to affect AppVeyor (Windows) or macOS/Linux though
![image](https://user-images.githubusercontent.com/2696087/37999166-7bbca418-31d6-11e8-8661-7c61daf2bc49.png)

**Comment by natemcmaster** [comment]
Result of conversation with MSBuild guys:

This is basically the same problem as https://github.com/Microsoft/vstest/issues/1503. We are doing things with MSBuild that are apparently bad to do. We got away with it until now because MSBuild for .NET Core didn't support node reuse. Now that MSBuild is shipping node reuse for core, the bad things we did have bitten us. We can workaround for now with `$env:MSBUILDENSURESTDOUTFORTASKPROCESSES=1`, but this workaround may go away at some point. We should try to do the Right Thing so we can enable node reuse in the future.

**Comment by ryanbrandenburg** [comment]
I'm un-blocking us by doing #TheWrongThing in #627, but I agree with @natemcmaster that we should change to doing the right thing once it's not blocking everyone else, so I propose leaving this issue open and just moving it to the RC1 milestone once my workaround merges.

For future reference, I believe that #TheRightThing is to redirect stdout and stderr in `RunBase` and attach those streams to events which write to MSBuild. It's my understanding that doing that will lose us some coloring and possibly cause difficulty with TC messages, which is why we don't want to do it right now.

**Comment by Eilon** [comment]
https://github.com/aspnet/BuildTools/pull/629

**Comment by Eilon** [comment]
Oops, bad copy/paste. Meant to say: @ryanbrandenburg - is there any further action required for this issue, or does https://github.com/aspnet/BuildTools/pull/629 cover it?

**Comment by ryanbrandenburg** [comment]
Yes, #629 is #TheRightThing.
