### ISSUE TITLE
ApiCheck should verify changes to AttributeUsage

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#652]
Removing an AttributeTarget or changing things like AllowMultiple (from true -> false) are all breaking changes. ApiCheck currently does not check these

**Comment by pranavkm** [comment]
cc @dougbu

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface (see #747). Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. Please reopen if this is urgent.
