### ISSUE TITLE
ApiCheck Generate shouldn't take ExcludeInternalsPublic parameter

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#693]
There is no scenario in which we want to generate the baselines without the Internal classes (only comparing them should matter). Lets remove that option entirely, as currently it makes the baselines generated by universe exclude them in order to run the check.

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface (see #747). Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. Please reopen if this is urgent.
