### ISSUE TITLE
ApiCheck creates baselines for nested protected/public classes inside internal classes

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/BuildTools#704]
It shouldn't care about anything inside an internal class.

Example,
https://github.com/aspnet/Razor/blob/master/src/Microsoft.AspNetCore.Razor.Language/baseline.netcore.json#L15346

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface (see #747). Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. Please reopen if this is urgent.
