### ISSUE TITLE
NuGet packages folder now has lowercase paths, which affects DependenciesPackager

### ISSUE THREAD

**Issue by joelverhagen** [aspnet/BuildTools#94]
Right now, the dependencies packager tool is constructing paths using `OriginalCase` package ID and version, not `lowercase` in two places: [hash path](https://github.com/aspnet/DnxTools/blob/0da7ded2c9a5368db95e078d4326f4426a473766/src/DependenciesPackager/Program.cs#L437-L438), [directory name](
https://github.com/aspnet/DnxTools/blob/0da7ded2c9a5368db95e078d4326f4426a473766/src/DependenciesPackager/Program.cs#L487-L488).

This change in NuGet, along with it's downstream affected parties is outlined here:
https://github.com/NuGet/Home/issues/2522

I think the right fix here it to consume NuGet APIs to build these paths, much like what .NET CLI is doing ([example](https://github.com/dotnet/cli/blob/c5b2da0db5ae73da6fbbdbcd279607149f7426f5/src/Microsoft.DotNet.ProjectModel/Resolution/PackageDependencyProvider.cs#L58)). The NuGet type to use is probably [`VersionFolderPathResolver`](https://github.com/NuGet/NuGet.Client/blob/7aa6498e6adabc00753181d295ff2b4f97bb9e44/src/NuGet.Core/NuGet.Packaging/VersionFolderPathResolver.cs).

If this work is not done, the `DOTNET_HOSTING_OPTIMIZATION_CACHE` on Linux will no longer work, since the `.deps.json` file of .NET Core 1.1.0 apps will have lowercase paths. Windows will keep working since it's a case-insensitive file system, but it should be fixed as well since this is basically just a convenient coincidence. From what I understand, this will not break the Linux app, it will just mean startup time is much slower.

/cc @troydai @javiercn

**Comment by muratg** [comment]
@troydai could you sync up with @victorhurdugaci and get this one? We may need to consume the new CLI to be able to do this, and not sure when that can happen.

cc @pranavkm

**Comment by troydai** [comment]
There are two solutions, we discussed.

1. Use NuGet.client's API to generate the package path. This is the better solution as it lifts the responsibility of path schema from tools. However, since the DependenciesPackager depends on 1.0.0-preview2 ProjectModel, it introduces conflict between NuGet 3.5.0-rc2-final and other NuGet version which 1.0.0-preview2 sdk depends on. So solve the conflict, the tools' dependencies need to be overhauled. Given that CLI SDK is still in the process of moving towards MSBuild (meaning project model may keep changing) this is a volatile I don't want to take.

2. Simply enforce lower case path every where. It is rough and inflexible. However it should solve the immediate problem.
